routes/web.php
<?php
// Route::get('/', function () { return redirect('/admin/home'); });

Route::get('/', 'HomeController@index');
Route::get('/speech', 'HomeController@speech');

// Route::get('/library', 'LibraryController@index');
Route::get('/library', 'LibraryController@index');
Route::get('/guide', 'GuideController@index');

Route::prefix('courses')->group(function(){
    Route::get('', ['uses' => 'CoursesController@index', 'as' => 'courses']);
    Route::get('{id}', ['uses' => 'CoursesController@show', 'as' => 'courses.show']);
    Route::get('start/{id}', 'CoursesController@start');
    Route::get('add/{id}', 'CoursesController@add');
    Route::get('remove/{id}', 'CoursesController@remove');
    Route::get('certificate/{id}', 'CoursesController@certificate'); 
    Route::get('done/{id}', 'CoursesController@done');
});

Route::prefix('trails')->group(function(){
    Route::get('', ['uses' => 'TrailsController@index', 'as' => 'trail']);
    Route::get('{id}', ['uses' => 'TrailsController@show', 'as' => 'trail.show']);
    Route::get('start/{id}', 'TrailsController@start');
    Route::get('add/{id}', 'TrailsController@add');
    Route::get('remove/{id}', 'TrailsController@remove');
    Route::get('certificate/{id}', 'TrailsController@certificate'); 
    Route::get('done/{id}', 'TrailsController@done');
});

Route::get('/logout', 'Auth\LoginController@logout');

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

// Registration Routes..
$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('auth.register');
$this->post('register', 'Auth\RegisterController@register')->name('auth.register');

// Social Login Routes..
Route::get('login/{driver}', 'Auth\LoginController@redirectToSocial')->name('auth.login.social');
Route::get('{driver}/callback', 'Auth\LoginController@handleSocialCallback')->name('auth.login.social_callback');

Route::group(['middleware' => ['auth', 'approved'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@home');
    // Route::get('/home', 'Admin\DashboardController@index');

    Route::resource('content_categories', 'Admin\ContentCategoriesController');
    Route::post('content_categories_mass_destroy', ['uses' => 'Admin\ContentCategoriesController@massDestroy', 'as' => 'content_categories.mass_destroy']);
    Route::resource('content_tags', 'Admin\ContentTagsController');
    Route::post('content_tags_mass_destroy', ['uses' => 'Admin\ContentTagsController@massDestroy', 'as' => 'content_tags.mass_destroy']);
    Route::resource('content_pages', 'Admin\ContentPagesController');
    Route::post('content_pages_mass_destroy', ['uses' => 'Admin\ContentPagesController@massDestroy', 'as' => 'content_pages.mass_destroy']);
    Route::get('internal_notifications/read', 'Admin\InternalNotificationsController@read');
    Route::resource('internal_notifications', 'Admin\InternalNotificationsController');
    Route::post('internal_notifications_mass_destroy', ['uses' => 'Admin\InternalNotificationsController@massDestroy', 'as' => 'internal_notifications.mass_destroy']);
    Route::resource('lessons', 'Admin\LessonsController');
    Route::post('lessons_mass_destroy', ['uses' => 'Admin\LessonsController@massDestroy', 'as' => 'lessons.mass_destroy']);
    Route::post('lessons_duplicate/{id}', ['uses' => 'Admin\LessonsController@duplicate', 'as' => 'lessons.duplicate']);
    Route::post('lessons_restore/{id}', ['uses' => 'Admin\LessonsController@restore', 'as' => 'lessons.restore']);
    Route::delete('lessons_perma_del/{id}', ['uses' => 'Admin\LessonsController@perma_del', 'as' => 'lessons.perma_del']);
    Route::resource('coursecategories', 'Admin\CoursecategoriesController');
    Route::post('coursecategories_mass_destroy', ['uses' => 'Admin\CoursecategoriesController@massDestroy', 'as' => 'coursecategories.mass_destroy']);
    Route::post('coursecategories_restore/{id}', ['uses' => 'Admin\CoursecategoriesController@restore', 'as' => 'coursecategories.restore']);
    Route::delete('coursecategories_perma_del/{id}', ['uses' => 'Admin\CoursecategoriesController@perma_del', 'as' => 'coursecategories.perma_del']);
    Route::resource('coursetags', 'Admin\CoursetagsController');
    Route::post('coursetags_mass_destroy', ['uses' => 'Admin\CoursetagsController@massDestroy', 'as' => 'coursetags.mass_destroy']);
    Route::post('coursetags_restore/{id}', ['uses' => 'Admin\CoursetagsController@restore', 'as' => 'coursetags.restore']);
    Route::delete('coursetags_perma_del/{id}', ['uses' => 'Admin\CoursetagsController@perma_del', 'as' => 'coursetags.perma_del']);
    Route::resource('courses', 'Admin\CoursesController');
    Route::post('courses_mass_destroy', ['uses' => 'Admin\CoursesController@massDestroy', 'as' => 'courses.mass_destroy']);
    Route::post('courses_restore/{id}', ['uses' => 'Admin\CoursesController@restore', 'as' => 'courses.restore']);
    Route::delete('courses_perma_del/{id}', ['uses' => 'Admin\CoursesController@perma_del', 'as' => 'courses.perma_del']);
    Route::resource('coursescertificates', 'Admin\CoursescertificatesController');
    Route::post('coursescertificates_mass_destroy', ['uses' => 'Admin\CoursescertificatesController@massDestroy', 'as' => 'coursescertificates.mass_destroy']);
    Route::post('coursescertificates_restore/{id}', ['uses' => 'Admin\CoursescertificatesController@restore', 'as' => 'coursescertificates.restore']);
    Route::delete('coursescertificates_perma_del/{id}', ['uses' => 'Admin\CoursescertificatesController@perma_del', 'as' => 'coursescertificates.perma_del']);
    Route::resource('faq_categories', 'Admin\FaqCategoriesController');
    Route::post('faq_categories_mass_destroy', ['uses' => 'Admin\FaqCategoriesController@massDestroy', 'as' => 'faq_categories.mass_destroy']);
    Route::resource('faq_questions', 'Admin\FaqQuestionsController');
    Route::post('faq_questions_mass_destroy', ['uses' => 'Admin\FaqQuestionsController@massDestroy', 'as' => 'faq_questions.mass_destroy']);
    Route::resource('generals', 'Admin\GeneralsController');
    Route::post('generals_mass_destroy', ['uses' => 'Admin\GeneralsController@massDestroy', 'as' => 'generals.mass_destroy']);
    Route::post('generals_restore/{id}', ['uses' => 'Admin\GeneralsController@restore', 'as' => 'generals.restore']);
    Route::delete('generals_perma_del/{id}', ['uses' => 'Admin\GeneralsController@perma_del', 'as' => 'generals.perma_del']);
    Route::resource('trailcategories', 'Admin\TrailcategoriesController');
    Route::post('trailcategories_mass_destroy', ['uses' => 'Admin\TrailcategoriesController@massDestroy', 'as' => 'trailcategories.mass_destroy']);
    Route::post('trailcategories_restore/{id}', ['uses' => 'Admin\TrailcategoriesController@restore', 'as' => 'trailcategories.restore']);
    Route::delete('trailcategories_perma_del/{id}', ['uses' => 'Admin\TrailcategoriesController@perma_del', 'as' => 'trailcategories.perma_del']);
    Route::resource('trailtags', 'Admin\TrailtagsController');
    Route::post('trailtags_mass_destroy', ['uses' => 'Admin\TrailtagsController@massDestroy', 'as' => 'trailtags.mass_destroy']);
    Route::post('trailtags_restore/{id}', ['uses' => 'Admin\TrailtagsController@restore', 'as' => 'trailtags.restore']);
    Route::delete('trailtags_perma_del/{id}', ['uses' => 'Admin\TrailtagsController@perma_del', 'as' => 'trailtags.perma_del']);
    Route::resource('trails', 'Admin\TrailsController');
    Route::post('trails_mass_destroy', ['uses' => 'Admin\TrailsController@massDestroy', 'as' => 'trails.mass_destroy']);
    Route::post('trails_restore/{id}', ['uses' => 'Admin\TrailsController@restore', 'as' => 'trails.restore']);
    Route::delete('trails_perma_del/{id}', ['uses' => 'Admin\TrailsController@perma_del', 'as' => 'trails.perma_del']);
    Route::resource('trailscertificates', 'Admin\TrailscertificatesController');
    Route::post('trailscertificates_mass_destroy', ['uses' => 'Admin\TrailscertificatesController@massDestroy', 'as' => 'trailscertificates.mass_destroy']);
    Route::post('trailscertificates_restore/{id}', ['uses' => 'Admin\TrailscertificatesController@restore', 'as' => 'trailscertificates.restore']);
    Route::delete('trailscertificates_perma_del/{id}', ['uses' => 'Admin\TrailscertificatesController@perma_del', 'as' => 'trailscertificates.perma_del']);
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('teams', 'Admin\TeamsController');
    Route::post('teams_mass_destroy', ['uses' => 'Admin\TeamsController@massDestroy', 'as' => 'teams.mass_destroy']);

app/Coursecategory.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Coursecategory
 *
 * @package App
 * @property string $title
 * @property string $slug
*/
class Coursecategory extends Model
{
    use SoftDeletes;

    protected $fillable = ['title', 'slug'];
    protected $hidden = [];
    public static $searchable = [
        'title',
        'slug',
    ];
    
    public static function boot()
    {
        parent::boot();

        Coursecategory::observe(new \App\Observers\UserActionsObserver);
    }
    
}

app/Http/Controllers/Admin/CoursecategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Coursecategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreCoursecategoriesRequest;
use App\Http\Requests\Admin\UpdateCoursecategoriesRequest;

use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
class CoursecategoriesController extends Controller
{
    /**
     * Display a listing of Coursecategory.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('coursecategory_access')) {
            return abort(401);
        }


        if (request('show_deleted') == 1) {
            if (! Gate::allows('coursecategory_delete')) {
                return abort(401);
            }
            $coursecategories = Coursecategory::onlyTrashed()->get();
        } else {
            $coursecategories = Coursecategory::all();
        }

        $generals = \App\General::get();

        return view('admin.coursecategories.index', compact('coursecategories', 'generals'));
    }

    /**
     * Show the form for creating new Coursecategory.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (! Gate::allows('coursecategory_create')) {
            return abort(401);
        }

        $generals = \App\General::get();

        return view('admin.coursecategories.create', compact('generals'));
    }

    /**
     * Store a newly created Coursecategory in storage.
     *
     * @param  \App\Http\Requests\StoreCoursecategoriesRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCoursecategoriesRequest $request)
    {
        if (! Gate::allows('coursecategory_create')) {
            return abort(401);
        }
        $coursecategory = Coursecategory::create($request->all());



        return redirect()->route('admin.coursecategories.index');
    }


    /**
     * Show the form for editing Coursecategory.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (! Gate::allows('coursecategory_edit')) {
            return abort(401);
        }
        $coursecategory = Coursecategory::findOrFail($id);

        $generals = \App\General::get();

        return view('admin.coursecategories.edit', compact('coursecategory', 'generals'));
    }

    /**
     * Update Coursecategory in storage.
     *
     * @param  \App\Http\Requests\UpdateCoursecategoriesRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCoursecategoriesRequest $request, $id)
    {
        if (! Gate::allows('coursecategory_edit')) {
            return abort(401);
        }
        $coursecategory = Coursecategory::findOrFail($id);
        $coursecategory->update($request->all());



        return redirect()->route('admin.coursecategories.index');
    }


    /**
     * Display Coursecategory.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (! Gate::allows('coursecategory_view')) {
            return abort(401);
        }
        $courses = \App\Course::whereHas('categories',
                    function ($query) use ($id) {
                        $query->where('id', $id);
                    })->get();

        $coursecategory = Coursecategory::findOrFail($id);

        $generals = \App\General::get();

        return view('admin.coursecategories.show', compact('coursecategory', 'courses', 'generals'));
    }


    /**
     * Remove Coursecategory from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (! Gate::allows('coursecategory_delete')) {
            return abort(401);
        }
        $coursecategory = Coursecategory::findOrFail($id);
        $coursecategory->delete();

        return redirect()->route('admin.coursecategories.index');
    }

    /**
     * Delete all selected Coursecategory at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        if (! Gate::allows('coursecategory_delete')) {
            return abort(401);
        }
        if ($request->input('ids')) {
            $entries = Coursecategory::whereIn('id', $request->input('ids'))->get();

            foreach ($entries as $entry) {
                $entry->delete();
            }
        }
    }


    /**
     * Restore Coursecategory from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function restore($id)
    {
        if (! Gate::allows('coursecategory_delete')) {
            return abort(401);
        }
        $coursecategory = Coursecategory::onlyTrashed()->findOrFail($id);
        $coursecategory->restore();

        return redirect()->route('admin.coursecategories.index');
    }

    /**
     * Permanently delete Coursecategory from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function perma_del($id)
    {
        if (! Gate::allows('coursecategory_delete')) {
            return abort(401);
        }
        $coursecategory = Coursecategory::onlyTrashed()->findOrFail($id);
        $coursecategory->forceDelete();

        return redirect()->route('admin.coursecategories.index');
    }
}

app/Http/Controllers/Api/V1/CoursecategoriesController.php
<?php

namespace App\Http\Controllers\Api\V1;

use App\Coursecategory;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreCoursecategoriesRequest;
use App\Http\Requests\Admin\UpdateCoursecategoriesRequest;
use Yajra\DataTables\DataTables;

use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
class CoursecategoriesController extends Controller
{
    public function index()
    {
        return Coursecategory::all();
    }

    public function show($id)
    {
        return Coursecategory::findOrFail($id);
    }

    public function update(UpdateCoursecategoriesRequest $request, $id)
    {
        $coursecategory = Coursecategory::findOrFail($id);
        $coursecategory->update($request->all());
        

        return $coursecategory;
    }

    public function store(StoreCoursecategoriesRequest $request)
    {
        $coursecategory = Coursecategory::create($request->all());
        

        return $coursecategory;
    }

    public function destroy($id)
    {
        $coursecategory = Coursecategory::findOrFail($id);
        $coursecategory->delete();
        return '';
    }
}

resources/views/admin/coursecategories/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="page-title">
        <div class="row">
            <div class="col s12 m9 l10"><h1>@lang('global.coursecategories.title')</h1>
                <ul>
                    <li>
                        <a href="{{ url('/admin/home') }}">
                            <i class="fa fa-home"></i>
                            Dashboard</a>
                    </li> /
                    <li>
                        <a href="{{ route('admin.coursecategories.index') }}">
                            @lang('global.coursecategories.title')</a>
                    </li> /
                    <li><span>@lang('global.app_create')</span></li>
                </ul>
            </div>
            <div class="col s12 m3 l2 right-align">
                <a href="{{ route('admin.coursecategories.index') }}" class="btn lighten-3 z-depth-0 chat-toggle">
                    @lang('global.app_back_to_list')
                </a>
            </div>
        </div>
    </div>


    {!! Form::open(['method' => 'POST', 'route' => ['admin.coursecategories.store']]) !!}
    <div class="row">
        <div class="col l9 m8 s12">
            <div class="card">
                <div class="title">
                    <h5>@lang('global.app_create')</h5>
                </div>

                <div class="content">
                    <div class="row">
                        <div class="col m9 s12">
                            <div class="input-field">
                                {!! Form::label('title', trans('global.coursecategories.fields.title').'') !!}
                                {!! Form::text('title', old('title'), ['class' => 'validate']) !!}
                                <span class="helper-text" data-error="@if($errors->has('title')){{ $errors->first('title') }}@endif" data-success="right"></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col l3 m4 s12">
            <div class="card">
                <div class="title">
                    <h5>Informations</h5>
                    <a class="minimize" href="#" draggable="false"><i class="mdi-navigation-expand-less"></i></a>
                </div>
                <div class="content">
                    <div class="col s12">
                        <div class="input-field">
                            {!! Form::label('slug', trans('global.coursecategories.fields.slug').'') !!}
                            {!! Form::text('slug', old('slug'), ['class' => 'validate']) !!}
                            <span class="helper-text" data-error="@if($errors->has('slug')){{ $errors->first('slug') }}@endif" data-success="right"></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s12">
                    {!! Form::button(trans('global.app_create') . '<i class="material-icons right">send</i>', ['class'=>'btn waves-effect waves-light right', 'type'=>'submit']) !!}
                </div>
            </div>
        </div>
    </div>
    {!! Form::close() !!}

@stop

resources/views/admin/coursecategories/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="page-title">
        <div class="row">
            <div class="col s12 m9 l10"><h1>@lang('global.coursecategories.title')</h1>
                <ul>
                    <li>
                        <a href="{{ url('/admin/home') }}">
                            <i class="fa fa-home"></i>
                            Dashboard</a>
                    </li> /
                    <li>
                        <a href="{{ route('admin.coursecategories.index') }}">
                            @lang('global.coursecategories.title')</a>
                    </li> /
                    <li><span>{{ $coursecategory->title }}</span></li>
                </ul>
            </div>
            <div class="col s12 m3 l2 right-align">
                <a href="{{ route('admin.coursecategories.index') }}" class="btn lighten-3 z-depth-0 chat-toggle">
                    @lang('global.app_back_to_list')
                </a>
            </div>
        </div>
    </div>

    <div class="card">
        <div class="title">
            <h5>@lang('global.app_view')</h5>
        </div>

        <div class="content">
            <div class="row">
                <div class="col s6">
                    <table class="table table-striped">
                        <tr>
                            <th>@lang('global.coursecategories.fields.title')</th>
                            <td field-key='title'>{{ $coursecategory->title }}</td>
                        </tr>
                        <tr>
                            <th>@lang('global.coursecategories.fields.slug')</th>
                            <td field-key='slug'>{{ $coursecategory->slug }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-tabs">
            <ul class="shuffle-tabs tabs tabs-fixed-width">
                <li class="tab grey-text"><a class="grey-text" href="#courses" aria-controls="courses">Courses</a></li>
            </ul>
        </div>

        <!-- Tab panes -->
        <div class="content">
            
            <div role="tabpanel" class="tab-pane active" id="courses">
                <table class="striped responsive-table {{ count($courses) > 0 ? 'datatable' : '' }}">
                    <thead>
                        <tr>
                            <th>@lang('global.courses.fields.order')</th>
                            <th></th>
                            <th>@lang('global.courses.fields.title')</th>
{{--                            <th>@lang('global.courses.fields.slug')</th>--}}
                            {{--<th>@lang('global.courses.fields.description')</th>--}}
                            {{--<th>@lang('global.courses.fields.introduction')</th>--}}
                            {{--<th>@lang('global.courses.fields.featured-image')</th>--}}
                            <th>@lang('global.courses.fields.instructor')</th>
                            {{--<th>@lang('global.courses.fields.lessons')</th>--}}
                            <th>@lang('global.courses.fields.duration')</th>
                            <th>@lang('global.courses.fields.start-date')</th>
                            <th>@lang('global.courses.fields.end-date')</th>
                            {{--<th>@lang('global.courses.fields.categories')</th>--}}
                            {{--<th>@lang('global.courses.fields.tags')</th>--}}
                            <th>@lang('global.courses.fields.approved')</th>
                            @if( request('show_deleted') == 1 )
                            <th>&nbsp;</th>
                            @else
                            <th>&nbsp;</th>
                            @endif
                        </tr>
                    </thead>

                    <tbody>
                        @if (count($courses) > 0)
                            @foreach ($courses as $course)
                                <tr data-entry-id="{{ $course->id }}">
                                    <td field-key='order'>{{ $course->order }}</td>
                                    <td></td>
                                    <td field-key='title'>{{ $course->title }}</td>
                                    {{--<td field-key='slug'>{{ $course->slug }}</td>--}}
                                    {{--<td field-key='description'>{!! $course->description !!}</td>--}}
                                    {{--<td field-key='introduction'>{!! $course->introduction !!}</td>--}}
                                    {{--<td field-key='featured_image'>@if($course->featured_image)<a href="{{ asset(env('UPLOAD_PATH').'/' . $course->featured_image) }}" target="_blank"><img src="{{ asset(env('UPLOAD_PATH').'/thumb/' . $course->featured_image) }}"/></a>@endif</td>--}}
                                    <td field-key='instructor'>
                                        @foreach ($course->instructor as $singleInstructor)
                                            <span class="label label-info label-many">{{ $singleInstructor->name }}</span>
                                        @endforeach
                                    </td>
                                    {{--<td field-key='lessons'>--}}
                                        {{--@foreach ($course->lessons as $singleLessons)--}}
                                            {{--<span class="label label-info label-many">{{ $singleLessons->title }}</span>--}}
                                        {{--@endforeach--}}
                                    {{--</td>--}}
                                    <td field-key='duration'>{{ $course->duration }}</td>
                                    <td field-key='start_date'>{{ $course->start_date }}</td>
                                    <td field-key='end_date'>{{ $course->end_date }}</td>
                                    {{--<td field-key='categories'>--}}
                                        {{--@foreach ($course->categories as $singleCategories)--}}
                                            {{--<span class="label label-info label-many">{{ $singleCategories->title }}</span>--}}
                                        {{--@endforeach--}}
                                    {{--</td>--}}
                                    {{--<td field-key='tags'>--}}
                                        {{--@foreach ($course->tags as $singleTags)--}}
                                            {{--<span class="label label-info label-many">{{ $singleTags->title }}</span>--}}
                                        {{--@endforeach--}}
                                    {{--</td>--}}
                                    <td field-key='approved'>{{ Form::checkbox("approved", 1, $course->approved == 1 ? true : false, ["disabled"]) }}</td>
                                    @if( request('show_deleted') == 1 )
                                    <td>
                                        {!! Form::open(array(
                                            'style' => 'display: inline-block;',
                                            'method' => 'POST',
                                            'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                            'route' => ['admin.courses.restore', $course->id])) !!}
                                        {!! Form::submit(trans('global.app_restore'), array('class' => 'btn-square blue-text')) !!}
                                        {!! Form::close() !!}
                                                                        {!! Form::open(array(
                                            'style' => 'display: inline-block;',
                                            'method' => 'DELETE',
                                            'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                            'route' => ['admin.courses.perma_del', $course->id])) !!}
                                        {!! Form::submit(trans('global.app_permadel'), array('class' => 'btn-square red-text')) !!}
                                        {!! Form::close() !!}
                                                                    </td>
                                    @else
                                    <td>
                                        <div class="buttons">
                                            @can('course_view')
                                            <a href="{{ route('admin.courses.show',[$course->id]) }}" class="waves-effect waves-light btn-small btn-square amber-text"><i class="material-icons">remove_red_eye</i></a>
                                            @endcan
                                            @can('course_edit')
                                            <a href="{{ route('admin.courses.edit',[$course->id]) }}" class="waves-effect waves-light btn-small btn-square blue-text"><i class="material-icons">edit</i></a>
                                            @endcan
                                            @can('course_delete')
                                            {!! Form::open(array(
                                                'style' => 'display: inline-block;',
                                                'method' => 'DELETE',
                                                'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                                'route' => ['admin.courses.destroy', $course->id])) !!}
                                            {!! Form::button('<i class="far fa-trash-alt"></i>', ['class'=>'waves-effect waves-light btn-small btn-square red-text', 'type'=>'submit']) !!}
                                            {!! Form::close() !!}
                                            @endcan
                                        </div>
                                    </td>
                                    @endif
                                </tr>
                            @endforeach
                        @else
                            <tr>
                                <td colspan="19">@lang('global.app_no_entries_in_table')</td>
                            </tr>
                        @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@stop