routes/web.php
<?php
// Route::get('/', function () { return redirect('/admin/home'); });

Route::get('/', 'HomeController@index');
Route::get('/speech', 'HomeController@speech');

// Route::get('/library', 'LibraryController@index');
Route::get('/library', 'LibraryController@index');
Route::get('/guide', 'GuideController@index');

Route::prefix('courses')->group(function(){
    Route::get('', ['uses' => 'CoursesController@index', 'as' => 'courses']);
    Route::get('{id}', ['uses' => 'CoursesController@show', 'as' => 'courses.show']);
    Route::get('start/{id}', 'CoursesController@start');
    Route::get('add/{id}', 'CoursesController@add');
    Route::get('remove/{id}', 'CoursesController@remove');
    Route::get('certificate/{id}', 'CoursesController@certificate'); 
    Route::get('done/{id}', 'CoursesController@done');
});

Route::prefix('trails')->group(function(){
    Route::get('', ['uses' => 'TrailsController@index', 'as' => 'trail']);
    Route::get('{id}', ['uses' => 'TrailsController@show', 'as' => 'trail.show']);
    Route::get('start/{id}', 'TrailsController@start');
    Route::get('add/{id}', 'TrailsController@add');
    Route::get('remove/{id}', 'TrailsController@remove');
    Route::get('certificate/{id}', 'TrailsController@certificate'); 
    Route::get('done/{id}', 'TrailsController@done');
});

Route::get('/logout', 'Auth\LoginController@logout');

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

// Registration Routes..
$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('auth.register');
$this->post('register', 'Auth\RegisterController@register')->name('auth.register');

// Social Login Routes..
Route::get('login/{driver}', 'Auth\LoginController@redirectToSocial')->name('auth.login.social');
Route::get('{driver}/callback', 'Auth\LoginController@handleSocialCallback')->name('auth.login.social_callback');

Route::group(['middleware' => ['auth', 'approved'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@home');
    // Route::get('/home', 'Admin\DashboardController@index');

    Route::resource('content_categories', 'Admin\ContentCategoriesController');
    Route::post('content_categories_mass_destroy', ['uses' => 'Admin\ContentCategoriesController@massDestroy', 'as' => 'content_categories.mass_destroy']);
    Route::resource('content_tags', 'Admin\ContentTagsController');
    Route::post('content_tags_mass_destroy', ['uses' => 'Admin\ContentTagsController@massDestroy', 'as' => 'content_tags.mass_destroy']);
    Route::resource('content_pages', 'Admin\ContentPagesController');
    Route::post('content_pages_mass_destroy', ['uses' => 'Admin\ContentPagesController@massDestroy', 'as' => 'content_pages.mass_destroy']);
    Route::get('internal_notifications/read', 'Admin\InternalNotificationsController@read');
    Route::resource('internal_notifications', 'Admin\InternalNotificationsController');
    Route::post('internal_notifications_mass_destroy', ['uses' => 'Admin\InternalNotificationsController@massDestroy', 'as' => 'internal_notifications.mass_destroy']);
    Route::resource('lessons', 'Admin\LessonsController');
    Route::post('lessons_mass_destroy', ['uses' => 'Admin\LessonsController@massDestroy', 'as' => 'lessons.mass_destroy']);
    Route::post('lessons_duplicate/{id}', ['uses' => 'Admin\LessonsController@duplicate', 'as' => 'lessons.duplicate']);
    Route::post('lessons_restore/{id}', ['uses' => 'Admin\LessonsController@restore', 'as' => 'lessons.restore']);
    Route::delete('lessons_perma_del/{id}', ['uses' => 'Admin\LessonsController@perma_del', 'as' => 'lessons.perma_del']);
    Route::resource('coursecategories', 'Admin\CoursecategoriesController');
    Route::post('coursecategories_mass_destroy', ['uses' => 'Admin\CoursecategoriesController@massDestroy', 'as' => 'coursecategories.mass_destroy']);
    Route::post('coursecategories_restore/{id}', ['uses' => 'Admin\CoursecategoriesController@restore', 'as' => 'coursecategories.restore']);
    Route::delete('coursecategories_perma_del/{id}', ['uses' => 'Admin\CoursecategoriesController@perma_del', 'as' => 'coursecategories.perma_del']);
    Route::resource('coursetags', 'Admin\CoursetagsController');
    Route::post('coursetags_mass_destroy', ['uses' => 'Admin\CoursetagsController@massDestroy', 'as' => 'coursetags.mass_destroy']);
    Route::post('coursetags_restore/{id}', ['uses' => 'Admin\CoursetagsController@restore', 'as' => 'coursetags.restore']);
    Route::delete('coursetags_perma_del/{id}', ['uses' => 'Admin\CoursetagsController@perma_del', 'as' => 'coursetags.perma_del']);
    Route::resource('courses', 'Admin\CoursesController');
    Route::post('courses_mass_destroy', ['uses' => 'Admin\CoursesController@massDestroy', 'as' => 'courses.mass_destroy']);
    Route::post('courses_restore/{id}', ['uses' => 'Admin\CoursesController@restore', 'as' => 'courses.restore']);
    Route::delete('courses_perma_del/{id}', ['uses' => 'Admin\CoursesController@perma_del', 'as' => 'courses.perma_del']);
    Route::resource('coursescertificates', 'Admin\CoursescertificatesController');
    Route::post('coursescertificates_mass_destroy', ['uses' => 'Admin\CoursescertificatesController@massDestroy', 'as' => 'coursescertificates.mass_destroy']);
    Route::post('coursescertificates_restore/{id}', ['uses' => 'Admin\CoursescertificatesController@restore', 'as' => 'coursescertificates.restore']);
    Route::delete('coursescertificates_perma_del/{id}', ['uses' => 'Admin\CoursescertificatesController@perma_del', 'as' => 'coursescertificates.perma_del']);
    Route::resource('faq_categories', 'Admin\FaqCategoriesController');
    Route::post('faq_categories_mass_destroy', ['uses' => 'Admin\FaqCategoriesController@massDestroy', 'as' => 'faq_categories.mass_destroy']);
    Route::resource('faq_questions', 'Admin\FaqQuestionsController');
    Route::post('faq_questions_mass_destroy', ['uses' => 'Admin\FaqQuestionsController@massDestroy', 'as' => 'faq_questions.mass_destroy']);
    Route::resource('generals', 'Admin\GeneralsController');
    Route::post('generals_mass_destroy', ['uses' => 'Admin\GeneralsController@massDestroy', 'as' => 'generals.mass_destroy']);
    Route::post('generals_restore/{id}', ['uses' => 'Admin\GeneralsController@restore', 'as' => 'generals.restore']);
    Route::delete('generals_perma_del/{id}', ['uses' => 'Admin\GeneralsController@perma_del', 'as' => 'generals.perma_del']);
    Route::resource('trailcategories', 'Admin\TrailcategoriesController');
    Route::post('trailcategories_mass_destroy', ['uses' => 'Admin\TrailcategoriesController@massDestroy', 'as' => 'trailcategories.mass_destroy']);
    Route::post('trailcategories_restore/{id}', ['uses' => 'Admin\TrailcategoriesController@restore', 'as' => 'trailcategories.restore']);
    Route::delete('trailcategories_perma_del/{id}', ['uses' => 'Admin\TrailcategoriesController@perma_del', 'as' => 'trailcategories.perma_del']);
    Route::resource('trailtags', 'Admin\TrailtagsController');
    Route::post('trailtags_mass_destroy', ['uses' => 'Admin\TrailtagsController@massDestroy', 'as' => 'trailtags.mass_destroy']);
    Route::post('trailtags_restore/{id}', ['uses' => 'Admin\TrailtagsController@restore', 'as' => 'trailtags.restore']);
    Route::delete('trailtags_perma_del/{id}', ['uses' => 'Admin\TrailtagsController@perma_del', 'as' => 'trailtags.perma_del']);
    Route::resource('trails', 'Admin\TrailsController');
    Route::post('trails_mass_destroy', ['uses' => 'Admin\TrailsController@massDestroy', 'as' => 'trails.mass_destroy']);
    Route::post('trails_restore/{id}', ['uses' => 'Admin\TrailsController@restore', 'as' => 'trails.restore']);
    Route::delete('trails_perma_del/{id}', ['uses' => 'Admin\TrailsController@perma_del', 'as' => 'trails.perma_del']);
    Route::resource('trailscertificates', 'Admin\TrailscertificatesController');
    Route::post('trailscertificates_mass_destroy', ['uses' => 'Admin\TrailscertificatesController@massDestroy', 'as' => 'trailscertificates.mass_destroy']);
    Route::post('trailscertificates_restore/{id}', ['uses' => 'Admin\TrailscertificatesController@restore', 'as' => 'trailscertificates.restore']);
    Route::delete('trailscertificates_perma_del/{id}', ['uses' => 'Admin\TrailscertificatesController@perma_del', 'as' => 'trailscertificates.perma_del']);
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('teams', 'Admin\TeamsController');
    Route::post('teams_mass_destroy', ['uses' => 'Admin\TeamsController@massDestroy', 'as' => 'teams.mass_destroy']);

app/FaqCategory.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Class FaqCategory
 *
 * @package App
 * @property string $title
*/
class FaqCategory extends Model
{
    protected $fillable = ['title'];
    protected $hidden = [];
    public static $searchable = [
    ];
    
    public static function boot()
    {
        parent::boot();

        FaqCategory::observe(new \App\Observers\UserActionsObserver);
    }
    
}

app/Http/Controllers/Admin/FaqCategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\FaqCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreFaqCategoriesRequest;
use App\Http\Requests\Admin\UpdateFaqCategoriesRequest;
use Yajra\DataTables\DataTables;

use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
class FaqCategoriesController extends Controller
{
    /**
     * Display a listing of FaqCategory.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('faq_category_access')) {
            return abort(401);
        }


        
        if (request()->ajax()) {
            $query = FaqCategory::query();
            $template = 'actionsTemplate';
            
            $query->select([
                'faq_categories.id',
                'faq_categories.title',
            ]);
            $table = Datatables::of($query);

            $table->setRowAttr([
                'data-entry-id' => '{{$id}}',
            ]);
            $table->addColumn('massDelete', '&nbsp;');
            $table->addColumn('actions', '&nbsp;');
            $table->editColumn('actions', function ($row) use ($template) {
                $gateKey  = 'faq_category_';
                $routeKey = 'admin.faq_categories';

                return view($template, compact('row', 'gateKey', 'routeKey'));
            });

            $table->rawColumns(['actions','massDelete']);

            return $table->make(true);
        }

        $generals = \App\General::get();

        return view('admin.faq_categories.index', compact('generals'));
    }

    /**
     * Show the form for creating new FaqCategory.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (! Gate::allows('faq_category_create')) {
            return abort(401);
        }

        $generals = \App\General::get();

        return view('admin.faq_categories.create', compact('generals'));
    }

    /**
     * Store a newly created FaqCategory in storage.
     *
     * @param  \App\Http\Requests\StoreFaqCategoriesRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreFaqCategoriesRequest $request)
    {
        if (! Gate::allows('faq_category_create')) {
            return abort(401);
        }
        $faq_category = FaqCategory::create($request->all());



        return redirect()->route('admin.faq_categories.index');
    }


    /**
     * Show the form for editing FaqCategory.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (! Gate::allows('faq_category_edit')) {
            return abort(401);
        }
        $faq_category = FaqCategory::findOrFail($id);

        $generals = \App\General::get();

        return view('admin.faq_categories.edit', compact('faq_category', 'generals'));
    }

    /**
     * Update FaqCategory in storage.
     *
     * @param  \App\Http\Requests\UpdateFaqCategoriesRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateFaqCategoriesRequest $request, $id)
    {
        if (! Gate::allows('faq_category_edit')) {
            return abort(401);
        }
        $faq_category = FaqCategory::findOrFail($id);
        $faq_category->update($request->all());



        return redirect()->route('admin.faq_categories.index');
    }


    /**
     * Display FaqCategory.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (! Gate::allows('faq_category_view')) {
            return abort(401);
        }
        $faq_questions = \App\FaqQuestion::where('category_id', $id)->get();

        $faq_category = FaqCategory::findOrFail($id);

        $generals = \App\General::get();

        return view('admin.faq_categories.show', compact('faq_category', 'faq_questions', 'generals'));
    }


    /**
     * Remove FaqCategory from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (! Gate::allows('faq_category_delete')) {
            return abort(401);
        }
        $faq_category = FaqCategory::findOrFail($id);
        $faq_category->delete();

        return redirect()->route('admin.faq_categories.index');
    }

    /**
     * Delete all selected FaqCategory at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        if (! Gate::allows('faq_category_delete')) {
            return abort(401);
        }
        if ($request->input('ids')) {
            $entries = FaqCategory::whereIn('id', $request->input('ids'))->get();

            foreach ($entries as $entry) {
                $entry->delete();
            }
        }
    }

}

resources/views/admin/faq_categories/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="page-title">
        <div class="row">
            <div class="col s12 m9 l10"><h1>@lang('global.faq-categories.title')</h1>
                <ul>
                    <li>
                        <a href="{{ url('/admin/home') }}">
                            <i class="fa fa-home"></i>
                            Dashboard</a>
                    </li> /
                    <li>
                        <a href="{{ route('admin.faq_categories.index') }}">
                            @lang('global.faq-categories.title')</a>
                    </li> /
                    <li><span>@lang('global.app_create')</span></li>
                </ul>
            </div>
            <div class="col s12 m3 l2 right-align">
                <a href="{{ route('admin.faq_categories.index') }}" class="btn lighten-3 z-depth-0 chat-toggle">
                    @lang('global.app_back_to_list')
                </a>
            </div>
        </div>
    </div>


    {!! Form::open(['method' => 'POST', 'route' => ['admin.faq_categories.store']]) !!}
    <div class="card">
        <div class="title">
            <h5>@lang('global.app_create')</h5>
        </div>
        
        <div class="content">
            <div class="row">
                <div class="col m6 s12">
                    {!! Form::label('title', trans('global.faq-categories.fields.title').'*') !!}
                    {!! Form::text('title', old('title'), ['class' => 'validate', 'required' => '']) !!}
                    <span class="helper-text" data-error="@if($errors->has('title')){{ $errors->first('title') }}@endif" data-success="right"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col s12">
            {!! Form::button(trans('global.app_create') . '<i class="material-icons right">send</i>', ['class'=>'btn waves-effect waves-light right', 'type'=>'submit']) !!}
        </div>
    </div>
    {!! Form::close() !!}

@stop

resources/views/admin/faq_categories/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="page-title">
        <div class="row">
            <div class="col s12 m9 l10"><h1>@lang('global.faq-categories.title')</h1>
                <ul>
                    <li>
                        <a href="{{ url('/admin/home') }}">
                            <i class="fa fa-home"></i>
                            Dashboard</a>
                    </li> /
                    <li>
                        <a href="{{ route('admin.faq_categories.index') }}">
                            @lang('global.faq-categories.title')</a>
                    </li> /
                    <li><span>@lang('global.app_edit')</span></li>
                </ul>
            </div>
            <div class="col s12 m3 l2 right-align">
                <a href="{{ route('admin.faq_categories.index') }}" class="btn lighten-3 z-depth-0 chat-toggle">
                    @lang('global.app_back_to_list')
                </a>
            </div>
        </div>
    </div>

    {!! Form::model($faq_category, ['method' => 'PUT', 'route' => ['admin.faq_categories.update', $faq_category->id]]) !!}
    <div class="card">
        <div class="title">
            <h5>@lang('global.app_edit')</h5>
        </div>

        <div class="content">
            <div class="row">
                <div class="col m6 s12">
                    {!! Form::label('title', trans('global.faq-categories.fields.title').'*') !!}
                    {!! Form::text('title', old('title'), ['class' => 'validate', 'required' => '']) !!}
                    <span class="helper-text" data-error="@if($errors->has('title')){{ $errors->first('title') }}@endif" data-success="right"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col s12">
            {!! Form::button(trans('global.app_update') . '<i class="material-icons right">send</i>', ['class'=>'btn waves-effect waves-light right', 'type'=>'submit']) !!}
        </div>
    </div>
    {!! Form::close() !!}
@stop

resources/views/admin/faq_categories/index.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')

@section('content')
    <div class="page-title">
        <div class="row">
            <div class="col s12 m8"><h1>@lang('global.faq-categories.title')</h1>
                <ul>
                    <li>
                        <a href="{{ url('/admin/home') }}">
                            <i class="fa fa-home"></i>
                            Dashboard</a>
                    </li> /
                    <li><span>@lang('global.faq-categories.title')</span></li>
                </ul>
            </div>
            <div class="col s12 m4 right-align">

                @can('faq_category_create')
                    <a href="{{ route('admin.faq_categories.create') }}" class="btn lighten-3 z-depth-0 chat-toggle">
                        Add Category
                    </a>
                @endcan
            </div>
        </div>
    </div>

    <div class="card">
        <div class="title">
            <h3>@lang('global.app_list')</h3>
        </div>

        <div class="content">
            <table class="no-order table table-striped ajaxTable @can('faq_category_delete') dt-select @else dt-show @endcan">
                <thead>
                    <tr>
                        <th></th>
                        @can('faq_category_delete')
                            <th><input type="checkbox" id="select-all" /><label for="select-all"></label></th>
                        @endcan

                        <th>@lang('global.faq-categories.fields.title')</th>
                        <th>&nbsp;</th>

                    </tr>
                </thead>
            </table>
        </div>
    </div>
@stop

@section('javascript')
    <script>
        @can('faq_category_delete')
            window.route_mass_crud_entries_destroy = '{{ route('admin.faq_categories.mass_destroy') }}';
        @endcan
        $(document).ready(function () {
            window.dtDefaultOptions.ajax = '{!! route('admin.faq_categories.index') !!}';
            window.dtDefaultOptions.columns = [
                {data: 'title', name: 'title'},
                @can('faq_category_delete')
                    {data: 'massDelete', name: 'id', searchable: false, sortable: false},
                @endcan
                {data: 'title', name: 'title'},
                
                {data: 'actions', name: 'actions', searchable: false, sortable: false}
            ];
            processAjaxTables();
        });
    </script>
@endsection

resources/views/admin/faq_categories/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="page-title">
        <div class="row">
            <div class="col s12 m9 l10"><h1>@lang('global.faq-categories.title')</h1>
                <ul>
                    <li>
                        <a href="{{ url('/admin/home') }}">
                            <i class="fa fa-home"></i>
                            Dashboard</a>
                    </li> /
                    <li>
                        <a href="{{ route('admin.faq_categories.index') }}">
                            @lang('global.faq-categories.title')</a>
                    </li> /
                    <li><span>{{ $faq_category->title }}</span></li>
                </ul>
            </div>
            <div class="col s12 m3 l2 right-align">
                <a href="{{ route('admin.faq_categories.index') }}" class="btn lighten-3 z-depth-0 chat-toggle">
                    @lang('global.app_back_to_list')
                </a>
            </div>
        </div>
    </div>

    <div class="card">
        <div class="title">
            <h5>@lang('global.app_view')</h5>
        </div>

        <div class="content">
            <div class="row">
                <div class="col s6">
                    <table class="table bordered striped">
                        <tr>
                            <th>@lang('global.faq-categories.fields.title')</th>
                            <td field-key='title'>{{ $faq_category->title }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-tabs">
            <ul class="shuffle-tabs tabs tabs-fixed-width">
                <li class="tab grey-text"><a class="grey-text" href="#faq_questions" aria-controls="faq_questions">Questions</a></li>
            </ul>
        </div>
        <div class="content">
            
            <div class="active" id="faq_questions">
                <table class="striped responsive-table {{ count($faq_questions) > 0 ? 'datatable' : '' }}">
                    <thead>
                        <tr>
                            <th></th>
                            <th></th>
                            <th>@lang('global.faq-questions.fields.category')</th>
                            <th>@lang('global.faq-questions.fields.question-text')</th>
                            <th>@lang('global.faq-questions.fields.answer-text')</th>
                            <th>&nbsp;</th>

                        </tr>
                    </thead>

                    <tbody>
                        @if (count($faq_questions) > 0)
                            @foreach ($faq_questions as $faq_question)
                                <tr data-entry-id="{{ $faq_question->id }}">
                                    <td></td>
                                    <td></td>
                                    <td field-key='category'>{{ $faq_question->category->title or '' }}</td>
                                    <td field-key='question_text'>{!! $faq_question->question_text !!}</td>
                                    <td field-key='answer_text'>{!! $faq_question->answer_text !!}</td>
                                    <td>
                                        <div class="buttons">
                                            @can('faq_question_view')
                                            <a href="{{ route('admin.faq_questions.show',[$faq_question->id]) }}" class="waves-effect waves-light btn-small btn-square amber-text"><i class="material-icons">remove_red_eye</i></a>
                                            @endcan
                                            @can('faq_question_edit')
                                            <a href="{{ route('admin.faq_questions.edit',[$faq_question->id]) }}" class="waves-effect waves-light btn-small btn-square blue-text"><i class="material-icons">edit</i></a>
                                            @endcan
                                            @can('faq_question_delete')
                                            {!! Form::open(array(
                                                'style' => 'display: inline-block;',
                                                'method' => 'DELETE',
                                                'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                                'route' => ['admin.faq_questions.destroy', $faq_question->id])) !!}
                                            {!! Form::button('<i class="far fa-trash-alt"></i>', ['class'=>'waves-effect waves-light btn-small btn-square red-text', 'type'=>'submit']) !!}
                                            {!! Form::close() !!}
                                            @endcan
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        @else
                            <tr>
                                <td colspan="8">@lang('global.app_no_entries_in_table')</td>
                            </tr>
                        @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@stop