routes/web.php
    Route::post('content_categories_mass_destroy', ['uses' => 'Admin\ContentCategoriesController@massDestroy', 'as' => 'content_categories.mass_destroy']);
    Route::resource('content_tags', 'Admin\ContentTagsController');
    Route::post('content_tags_mass_destroy', ['uses' => 'Admin\ContentTagsController@massDestroy', 'as' => 'content_tags.mass_destroy']);
    Route::resource('content_pages', 'Admin\ContentPagesController');
    Route::post('content_pages_mass_destroy', ['uses' => 'Admin\ContentPagesController@massDestroy', 'as' => 'content_pages.mass_destroy']);
    Route::get('internal_notifications/read', 'Admin\InternalNotificationsController@read');
    Route::resource('internal_notifications', 'Admin\InternalNotificationsController');
    Route::post('internal_notifications_mass_destroy', ['uses' => 'Admin\InternalNotificationsController@massDestroy', 'as' => 'internal_notifications.mass_destroy']);
    Route::resource('lessons', 'Admin\LessonsController');
    Route::post('lessons_mass_destroy', ['uses' => 'Admin\LessonsController@massDestroy', 'as' => 'lessons.mass_destroy']);
    Route::post('lessons_duplicate/{id}', ['uses' => 'Admin\LessonsController@duplicate', 'as' => 'lessons.duplicate']);
    Route::post('lessons_restore/{id}', ['uses' => 'Admin\LessonsController@restore', 'as' => 'lessons.restore']);
    Route::delete('lessons_perma_del/{id}', ['uses' => 'Admin\LessonsController@perma_del', 'as' => 'lessons.perma_del']);
    Route::resource('coursecategories', 'Admin\CoursecategoriesController');
    Route::post('coursecategories_mass_destroy', ['uses' => 'Admin\CoursecategoriesController@massDestroy', 'as' => 'coursecategories.mass_destroy']);
    Route::post('coursecategories_restore/{id}', ['uses' => 'Admin\CoursecategoriesController@restore', 'as' => 'coursecategories.restore']);
    Route::delete('coursecategories_perma_del/{id}', ['uses' => 'Admin\CoursecategoriesController@perma_del', 'as' => 'coursecategories.perma_del']);
    Route::resource('coursetags', 'Admin\CoursetagsController');
    Route::post('coursetags_mass_destroy', ['uses' => 'Admin\CoursetagsController@massDestroy', 'as' => 'coursetags.mass_destroy']);
    Route::post('coursetags_restore/{id}', ['uses' => 'Admin\CoursetagsController@restore', 'as' => 'coursetags.restore']);
    Route::delete('coursetags_perma_del/{id}', ['uses' => 'Admin\CoursetagsController@perma_del', 'as' => 'coursetags.perma_del']);
    Route::resource('courses', 'Admin\CoursesController');
    Route::post('courses_mass_destroy', ['uses' => 'Admin\CoursesController@massDestroy', 'as' => 'courses.mass_destroy']);
    Route::post('courses_restore/{id}', ['uses' => 'Admin\CoursesController@restore', 'as' => 'courses.restore']);
    Route::delete('courses_perma_del/{id}', ['uses' => 'Admin\CoursesController@perma_del', 'as' => 'courses.perma_del']);
    Route::resource('coursescertificates', 'Admin\CoursescertificatesController');
    Route::post('coursescertificates_mass_destroy', ['uses' => 'Admin\CoursescertificatesController@massDestroy', 'as' => 'coursescertificates.mass_destroy']);
    Route::post('coursescertificates_restore/{id}', ['uses' => 'Admin\CoursescertificatesController@restore', 'as' => 'coursescertificates.restore']);
    Route::delete('coursescertificates_perma_del/{id}', ['uses' => 'Admin\CoursescertificatesController@perma_del', 'as' => 'coursescertificates.perma_del']);
    Route::resource('faq_categories', 'Admin\FaqCategoriesController');
    Route::post('faq_categories_mass_destroy', ['uses' => 'Admin\FaqCategoriesController@massDestroy', 'as' => 'faq_categories.mass_destroy']);
    Route::resource('faq_questions', 'Admin\FaqQuestionsController');
    Route::post('faq_questions_mass_destroy', ['uses' => 'Admin\FaqQuestionsController@massDestroy', 'as' => 'faq_questions.mass_destroy']);
    Route::resource('generals', 'Admin\GeneralsController');
    Route::post('generals_mass_destroy', ['uses' => 'Admin\GeneralsController@massDestroy', 'as' => 'generals.mass_destroy']);
    Route::post('generals_restore/{id}', ['uses' => 'Admin\GeneralsController@restore', 'as' => 'generals.restore']);
    Route::delete('generals_perma_del/{id}', ['uses' => 'Admin\GeneralsController@perma_del', 'as' => 'generals.perma_del']);
    Route::resource('trailcategories', 'Admin\TrailcategoriesController');
    Route::post('trailcategories_mass_destroy', ['uses' => 'Admin\TrailcategoriesController@massDestroy', 'as' => 'trailcategories.mass_destroy']);
    Route::post('trailcategories_restore/{id}', ['uses' => 'Admin\TrailcategoriesController@restore', 'as' => 'trailcategories.restore']);
    Route::delete('trailcategories_perma_del/{id}', ['uses' => 'Admin\TrailcategoriesController@perma_del', 'as' => 'trailcategories.perma_del']);
    Route::resource('trailtags', 'Admin\TrailtagsController');
    Route::post('trailtags_mass_destroy', ['uses' => 'Admin\TrailtagsController@massDestroy', 'as' => 'trailtags.mass_destroy']);
    Route::post('trailtags_restore/{id}', ['uses' => 'Admin\TrailtagsController@restore', 'as' => 'trailtags.restore']);
    Route::delete('trailtags_perma_del/{id}', ['uses' => 'Admin\TrailtagsController@perma_del', 'as' => 'trailtags.perma_del']);
    Route::resource('trails', 'Admin\TrailsController');
    Route::post('trails_mass_destroy', ['uses' => 'Admin\TrailsController@massDestroy', 'as' => 'trails.mass_destroy']);
    Route::post('trails_restore/{id}', ['uses' => 'Admin\TrailsController@restore', 'as' => 'trails.restore']);
    Route::delete('trails_perma_del/{id}', ['uses' => 'Admin\TrailsController@perma_del', 'as' => 'trails.perma_del']);
    Route::resource('trailscertificates', 'Admin\TrailscertificatesController');
    Route::post('trailscertificates_mass_destroy', ['uses' => 'Admin\TrailscertificatesController@massDestroy', 'as' => 'trailscertificates.mass_destroy']);
    Route::post('trailscertificates_restore/{id}', ['uses' => 'Admin\TrailscertificatesController@restore', 'as' => 'trailscertificates.restore']);
    Route::delete('trailscertificates_perma_del/{id}', ['uses' => 'Admin\TrailscertificatesController@perma_del', 'as' => 'trailscertificates.perma_del']);
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('teams', 'Admin\TeamsController');
    Route::post('teams_mass_destroy', ['uses' => 'Admin\TeamsController@massDestroy', 'as' => 'teams.mass_destroy']);
    Route::resource('user_actions', 'Admin\UserActionsController');
    Route::resource('datatrails', 'Admin\DatatrailsController');
    Route::post('datatrails_mass_destroy', ['uses' => 'Admin\DatatrailsController@massDestroy', 'as' => 'datatrails.mass_destroy']);
    Route::post('datatrails_restore/{id}', ['uses' => 'Admin\DatatrailsController@restore', 'as' => 'datatrails.restore']);
    Route::delete('datatrails_perma_del/{id}', ['uses' => 'Admin\DatatrailsController@perma_del', 'as' => 'datatrails.perma_del']);
    Route::resource('datacourses', 'Admin\DatacoursesController');
    Route::post('datacourses_mass_destroy', ['uses' => 'Admin\DatacoursesController@massDestroy', 'as' => 'datacourses.mass_destroy']);
    Route::post('datacourses_restore/{id}', ['uses' => 'Admin\DatacoursesController@restore', 'as' => 'datacourses.restore']);
    Route::delete('datacourses_perma_del/{id}', ['uses' => 'Admin\DatacoursesController@perma_del', 'as' => 'datacourses.perma_del']);

    Route::resource('datalessons', 'Admin\DatalessonsController');
    Route::post('datalessons_mass_destroy', ['uses' => 'Admin\DatalessonsController@massDestroy', 'as' => 'datalessons.mass_destroy']);
    Route::post('datalessons_restore/{id}', ['uses' => 'Admin\DatalessonsController@restore', 'as' => 'datalessons.restore']);
    Route::delete('datalessons_perma_del/{id}', ['uses' => 'Admin\DatalessonsController@perma_del', 'as' => 'datalessons.perma_del']);


    Route::resource('tests', 'Admin\TestsController');
    Route::resource('roles', 'Admin\RolesController');
    Route::resource('topics', 'Admin\TopicsController');
    Route::resource('questions', 'Admin\QuestionsController');
    Route::resource('questions_options', 'Admin\QuestionsOptionsController');
    Route::resource('results', 'Admin\ResultsController');

    Route::post('topics_mass_destroy', ['uses' => 'Admin\TopicsController@massDestroy', 'as' => 'topics.mass_destroy']);
    Route::post('questions_mass_destroy', ['uses' => 'Admin\QuestionsController@massDestroy', 'as' => 'questions.mass_destroy']);
    Route::post('questions_options_mass_destroy', ['uses' => 'Admin\QuestionsOptionsController@massDestroy', 'as' => 'questions_options.mass_destroy']);
    Route::post('results_mass_destroy', ['uses' => 'Admin\ResultsController@massDestroy', 'as' => 'results.mass_destroy']);

    Route::model('messenger', 'App\MessengerTopic');
    Route::get('messenger/inbox', 'Admin\MessengerController@inbox')->name('messenger.inbox');
    Route::get('messenger/outbox', 'Admin\MessengerController@outbox')->name('messenger.outbox');
    Route::resource('messenger', 'Admin\MessengerController');

    Route::get('testimonal', 'HomeController@testimonal');
    Route::post('savecoursefeedback', 'HomeController@savecoursefeedback')->name('savecoursefeedback');
    Route::post('savetrailfeedback', 'HomeController@savetrailfeedback')->name('savetrailfeedback');

    Route::get('search', 'MegaSearchController@search')->name('mega-search');
    Route::get('language/{lang}', function ($lang) {

app/Team.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Team
 *
 * @package App
 * @property string $name
*/
class Team extends Model
{
    protected $fillable = ['name'];
    protected $hidden = [];
    public static $searchable = [
    ];
    
    public static function boot()
    {
        parent::boot();

        Team::observe(new \App\Observers\UserActionsObserver);
    }
    
}

app/Http/Controllers/Admin/TeamsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Team;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreTeamsRequest;
use App\Http\Requests\Admin\UpdateTeamsRequest;

use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
class TeamsController extends Controller
{
    /**
     * Display a listing of Team.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('team_access')) {
            return abort(401);
        }

        $generals = \App\General::get();
                $teams = Team::all();

        return view('admin.teams.index', compact('teams', 'generals'));
    }

    /**
     * Show the form for creating new Team.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (! Gate::allows('team_create')) {
            return abort(401);
        }

        $generals = \App\General::get();

        return view('admin.teams.create', compact('generals'));
    }

    /**
     * Store a newly created Team in storage.
     *
     * @param  \App\Http\Requests\StoreTeamsRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreTeamsRequest $request)
    {
        if (! Gate::allows('team_create')) {
            return abort(401);
        }
        $team = Team::create($request->all());



        return redirect()->route('admin.teams.index');
    }


    /**
     * Show the form for editing Team.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (! Gate::allows('team_edit')) {
            return abort(401);
        }
        $team = Team::findOrFail($id);

        $generals = \App\General::get();

        return view('admin.teams.edit', compact('team', 'generals'));
    }

    /**
     * Update Team in storage.
     *
     * @param  \App\Http\Requests\UpdateTeamsRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateTeamsRequest $request, $id)
    {
        if (! Gate::allows('team_edit')) {
            return abort(401);
        }
        $team = Team::findOrFail($id);
        $team->update($request->all());



        return redirect()->route('admin.teams.index');
    }


    /**
     * Display Team.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (! Gate::allows('team_view')) {
            return abort(401);
        }
        $users = \App\User::where('team_id', $id)->get();

        $team = Team::findOrFail($id);

        $generals = \App\General::get();

        return view('admin.teams.show', compact('team', 'users', 'generals'));
    }


    /**
     * Remove Team from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (! Gate::allows('team_delete')) {
            return abort(401);
        }
        $team = Team::findOrFail($id);
        $team->delete();

        return redirect()->route('admin.teams.index');
    }

    /**
     * Delete all selected Team at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        if (! Gate::allows('team_delete')) {
            return abort(401);
        }
        if ($request->input('ids')) {
            $entries = Team::whereIn('id', $request->input('ids'))->get();

            foreach ($entries as $entry) {
                $entry->delete();
            }
        }
    }

}

resources/views/admin/teams/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="page-title">
        <div class="row">
            <div class="col s12 m9 l10"><h1>@lang('global.teams.title')</h1>
                <ul>
                    <li>
                        <a href="{{ url('/admin/home') }}">
                            <i class="fa fa-home"></i>
                            Dashboard</a>
                    </li> /
                    <li>
                        <a href="{{ route('admin.teams.index') }}">
                            @lang('global.teams.title')</a>
                    </li> /
                    <li><span>@lang('global.app_create')</span></li>
                </ul>
            </div>
            <div class="col s12 m3 l2 right-align">
                <a href="{{ route('admin.teams.index') }}" class="btn lighten-3 z-depth-0 chat-toggle">
                    @lang('global.app_back_to_list')
                </a>
            </div>
        </div>
    </div>

    {!! Form::open(['method' => 'POST', 'route' => ['admin.teams.store']]) !!}
    <div class="card">
        <div class="title">
            <h5>@lang('global.app_create')</h5>
        </div>
        
        <div class="content">
            <div class="row">
                <div class="col m6 s12">
                    {!! Form::label('name', trans('global.teams.fields.name').'*') !!}
                    {!! Form::text('name', old('name'), ['class' => 'validate', 'required' => '']) !!}
                    <span class="helper-text" data-error="@if($errors->has('name')){{ $errors->first('name') }}@endif" data-success="right"></span>
                </div>
            </div>

        </div>
    </div>
    <div class="row">
        <div class="col s12">
            {!! Form::button(trans('global.app_create') . '<i class="material-icons right">send</i>', ['class'=>'btn waves-effect waves-light right', 'type'=>'submit']) !!}
        </div>
    </div>
    {!! Form::close() !!}

@stop

resources/views/admin/teams/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="page-title">
        <div class="row">
            <div class="col s12 m9 l10"><h1>@lang('global.teams.title')</h1>
                <ul>
                    <li>
                        <a href="{{ url('/admin/home') }}">
                            <i class="fa fa-home"></i>
                            Dashboard</a>
                    </li> /
                    <li>
                        <a href="{{ route('admin.teams.index') }}">
                            @lang('global.teams.title')</a>
                    </li> /
                    <li><span>@lang('global.app_create')</span></li>
                </ul>
            </div>
            <div class="col s12 m3 l2 right-align">
                <a href="{{ route('admin.teams.index') }}" class="btn lighten-3 z-depth-0 chat-toggle">
                    @lang('global.app_back_to_list')
                </a>
            </div>
        </div>
    </div>

    {!! Form::model($team, ['method' => 'PUT', 'route' => ['admin.teams.update', $team->id]]) !!}
    <div class="card">
        <div class="title">
            <h5>@lang('global.app_edit')</h5>
        </div>

        <div class="content">
            <div class="row">
                <div class="col m6 s12">
                    {!! Form::label('name', trans('global.teams.fields.name').'*') !!}
                    {!! Form::text('name', old('name'), ['class' => 'validate', 'required' => '']) !!}
                    <span class="helper-text" data-error="@if($errors->has('name')){{ $errors->first('name') }}@endif" data-success="right"></span>
                </div>
            </div>

        </div>
    </div>
    <div class="row">
        <div class="col s12">
            {!! Form::button(trans('global.app_update') . '<i class="material-icons right">send</i>', ['class'=>'btn waves-effect waves-light right', 'type'=>'submit']) !!}
        </div>
    </div>
    {!! Form::close() !!}
@stop

resources/views/admin/teams/index.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')

@section('content')
    <div class="page-title">
        <div class="row">
            <div class="col s12 m9 l10"><h1>@lang('global.teams.title')</h1>
                <ul>
                    <li>
                        <a href="{{ url('/admin/home') }}">
                            <i class="fa fa-home"></i>
                            Dashboard</a>
                    </li> /
                    <li><span>@lang('global.teams.title')</span></li>
                </ul>
            </div>
            <div class="col s12 m3 l2 right-align">

                @can('team_create')
                    <a href="{{ route('admin.teams.create') }}" class="btn lighten-3 z-depth-0 chat-toggle">
                        Add Team
                    </a>
                @endcan
            </div>
        </div>
    </div>

    <div class="card">
        <div class="title">
            <h3>@lang('global.app_list')</h3>
        </div>

        <div class="content">
            <table class="table table-striped no-order {{ count($teams) > 0 ? 'datatable' : '' }} @can('team_delete') dt-select @else dt-show @endcan">
                <thead>
                    <tr>
                        <th>@lang('global.app_order')</th>
                        @can('team_delete')
                            <th><input type="checkbox" id="select-all" /><label for="select-all"></label></th>
                        @endcan

                        <th>@lang('global.teams.fields.name')</th>
                        <th>&nbsp;</th>

                    </tr>
                </thead>
                
                <tbody>
                    @if (count($teams) > 0)
                        @foreach ($teams as $team)
                            <tr data-entry-id="{{ $team->id }}">
                                <td>1</td>
                                @can('team_delete')
                                    <td></td>
                                @endcan
                                <td field-key='name'>{{ $team->name }}</td>
                                <td>
                                    <div class="buttons d-flex justify-content-center">
                                        @can('team_view')
                                        <a href="{{ route('admin.teams.show',[$team->id]) }}" class="waves-effect waves-light btn-small btn-square amber-text"><i class="material-icons">remove_red_eye</i></a>
                                        @endcan
                                        @can('team_edit')
                                        <a href="{{ route('admin.teams.edit',[$team->id]) }}" class="waves-effect waves-light btn-small btn-square blue-text"><i class="material-icons">edit</i></a>
                                        @endcan
                                        @can('team_delete')
                                        {!! Form::open(array(
                                            'style' => 'display: inline-block;',
                                            'method' => 'DELETE',
                                            'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                            'route' => ['admin.teams.destroy', $team->id])) !!}
                                                {!! Form::button('<i class="far fa-trash-alt"></i>', ['class'=>'waves-effect waves-light btn-small btn-square red-text', 'type'=>'submit']) !!}
                                        {!! Form::close() !!}
                                        @endcan
                                    </div>
                                </td>

                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="6">@lang('global.app_no_entries_in_table')</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
@stop

@section('javascript') 
    <script>
        @can('team_delete')
            window.route_mass_crud_entries_destroy = '{{ route('admin.teams.mass_destroy') }}';
        @endcan

    </script>
@endsection

resources/views/admin/teams/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="page-title">
        <div class="row">
            <div class="col s12 m9 l10"><h1>@lang('global.roles.title')</h1>
                <ul>
                    <li>
                        <a href="{{ url('/admin/home') }}">
                            <i class="fa fa-home"></i>
                            Dashboard</a>
                    </li> /
                    <li>
                        <a href="{{ route('admin.teams.index') }}">
                            @lang('global.roles.title')</a>
                    </li> /
                    <li><span>{{ $team->name }}</span></li>
                </ul>
            </div>
            <div class="col s12 m3 l2 right-align">
                <a href="{{ route('admin.roles.index') }}" class="btn lighten-3 z-depth-0 chat-toggle">
                    @lang('global.app_back_to_list')
                </a>
            </div>
        </div>
    </div>

    <div class="card">
        <div class="title">
            <h5>@lang('global.app_view')</h5>
        </div>

        <div class="content">
            <div class="row">
                <div class="col s6">
                    <table class="striped">
                        <tr>
                            <th>@lang('global.teams.fields.name')</th>
                            <td field-key='name'>{{ $team->name }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-tabs">
            <ul class="shuffle-tabs tabs tabs-fixed-width">
                <li class="tab grey-text"><a class="grey-text" href="#users">Users</a></li>
            </ul>
        </div>
        <div class="content">
    
            <div role="tabpanel" class="tab-pane active" id="users">
                <table class="striped responsive-table {{ count($users) > 0 ? 'datatable' : '' }}">
                    <thead>
                        <tr>
                            <th>@lang('global.users.fields.name')</th>
                            <th>@lang('global.users.fields.lastname')</th>
                            <th>@lang('global.users.fields.website')</th>
                            <th>@lang('global.users.fields.email')</th>
                            <th>@lang('global.users.fields.avatar')</th>
                            <th>@lang('global.users.fields.role')</th>
                            <th>@lang('global.users.fields.team')</th>
                            <th>@lang('global.users.fields.approved')</th>
                            <th>&nbsp;</th>

                        </tr>
                    </thead>

                    <tbody>
                        @if (count($users) > 0)
                            @foreach ($users as $user)
                                <tr data-entry-id="{{ $user->id }}">
                                    <td field-key='name'>{{ $user->name }}</td>
                                    <td field-key='lastname'>{{ $user->lastname }}</td>
                                    <td field-key='website'>{{ $user->website }}</td>
                                    <td field-key='email'>{{ $user->email }}</td>
                                    <td field-key='avatar'>@if($user->avatar)<a href="{{ asset(env('UPLOAD_PATH').'/' . $user->avatar) }}" target="_blank"><img src="{{ asset(env('UPLOAD_PATH').'/thumb/' . $user->avatar) }}"/></a>@endif</td>
                                    <td field-key='role'>
                                        @foreach ($user->role as $singleRole)
                                            <span class="label label-info label-many">{{ $singleRole->title }}</span>
                                        @endforeach
                                    </td>
                                    <td field-key='team'>{{ $user->team->name or '' }}</td>
                                    <td field-key='approved'>{{ Form::checkbox("approved", 1, $user->approved == 1 ? true : false, ["disabled"]) }}</td>
                                    <td>
                                        <div class="buttons">
                                            @can('user_view')
                                            <a href="{{ route('admin.users.show',[$user->id]) }}" class="waves-effect waves-light btn-small btn-square amber-text"><i class="material-icons">remove_red_eye</i></a>
                                            @endcan
                                            @can('user_edit')
                                            <a href="{{ route('admin.users.edit',[$user->id]) }}" class="waves-effect waves-light btn-small btn-square blue-text"><i class="material-icons">edit</i></a>
                                            @endcan
                                            @can('user_delete')
                                            {!! Form::open(array(
                                                'style' => 'display: inline-block;',
                                                'method' => 'DELETE',
                                                'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                                'route' => ['admin.users.destroy', $user->id])) !!}
                                            {!! Form::button('<i class="far fa-trash-alt"></i>', ['class'=>'waves-effect waves-light btn-small btn-square red-text', 'type'=>'submit']) !!}
                                            {!! Form::close() !!}
                                            @endcan
                                        </div>
                                    </td>

                                </tr>
                            @endforeach
                        @else
                            <tr>
                                <td colspan="15">@lang('global.app_no_entries_in_table')</td>
                            </tr>
                        @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@stop