routes/web.php
<?php
// Route::get('/', function () { return redirect('/admin/home'); });

Route::get('/', 'HomeController@index');
Route::get('/speech', 'HomeController@speech');

// Route::get('/library', 'LibraryController@index');
Route::get('/library', 'LibraryController@index');
Route::get('/guide', 'GuideController@index');

Route::prefix('courses')->group(function(){
    Route::get('', ['uses' => 'CoursesController@index', 'as' => 'courses']);
    Route::get('{id}', ['uses' => 'CoursesController@show', 'as' => 'courses.show']);
    Route::get('start/{id}', 'CoursesController@start');
    Route::get('add/{id}', 'CoursesController@add');
    Route::get('remove/{id}', 'CoursesController@remove');
    Route::get('certificate/{id}', 'CoursesController@certificate'); 
    Route::get('done/{id}', 'CoursesController@done');
});

Route::prefix('trails')->group(function(){
    Route::get('', ['uses' => 'TrailsController@index', 'as' => 'trail']);
    Route::get('{id}', ['uses' => 'TrailsController@show', 'as' => 'trail.show']);
    Route::get('start/{id}', 'TrailsController@start');
    Route::get('add/{id}', 'TrailsController@add');
    Route::get('remove/{id}', 'TrailsController@remove');
    Route::get('certificate/{id}', 'TrailsController@certificate'); 
    Route::get('done/{id}', 'TrailsController@done');
});

Route::get('/logout', 'Auth\LoginController@logout');

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

// Registration Routes..
$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('auth.register');
$this->post('register', 'Auth\RegisterController@register')->name('auth.register');

// Social Login Routes..
Route::get('login/{driver}', 'Auth\LoginController@redirectToSocial')->name('auth.login.social');
Route::get('{driver}/callback', 'Auth\LoginController@handleSocialCallback')->name('auth.login.social_callback');

Route::group(['middleware' => ['auth', 'approved'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@home');
    // Route::get('/home', 'Admin\DashboardController@index');

    Route::resource('content_categories', 'Admin\ContentCategoriesController');
    Route::post('content_categories_mass_destroy', ['uses' => 'Admin\ContentCategoriesController@massDestroy', 'as' => 'content_categories.mass_destroy']);
    Route::resource('content_tags', 'Admin\ContentTagsController');
    Route::post('content_tags_mass_destroy', ['uses' => 'Admin\ContentTagsController@massDestroy', 'as' => 'content_tags.mass_destroy']);
    Route::resource('content_pages', 'Admin\ContentPagesController');
    Route::post('content_pages_mass_destroy', ['uses' => 'Admin\ContentPagesController@massDestroy', 'as' => 'content_pages.mass_destroy']);
    Route::get('internal_notifications/read', 'Admin\InternalNotificationsController@read');
    Route::resource('internal_notifications', 'Admin\InternalNotificationsController');
    Route::post('internal_notifications_mass_destroy', ['uses' => 'Admin\InternalNotificationsController@massDestroy', 'as' => 'internal_notifications.mass_destroy']);
    Route::resource('lessons', 'Admin\LessonsController');
    Route::post('lessons_mass_destroy', ['uses' => 'Admin\LessonsController@massDestroy', 'as' => 'lessons.mass_destroy']);
    Route::post('lessons_duplicate/{id}', ['uses' => 'Admin\LessonsController@duplicate', 'as' => 'lessons.duplicate']);
    Route::post('lessons_restore/{id}', ['uses' => 'Admin\LessonsController@restore', 'as' => 'lessons.restore']);
    Route::delete('lessons_perma_del/{id}', ['uses' => 'Admin\LessonsController@perma_del', 'as' => 'lessons.perma_del']);
    Route::resource('coursecategories', 'Admin\CoursecategoriesController');
    Route::post('coursecategories_mass_destroy', ['uses' => 'Admin\CoursecategoriesController@massDestroy', 'as' => 'coursecategories.mass_destroy']);
    Route::post('coursecategories_restore/{id}', ['uses' => 'Admin\CoursecategoriesController@restore', 'as' => 'coursecategories.restore']);
    Route::delete('coursecategories_perma_del/{id}', ['uses' => 'Admin\CoursecategoriesController@perma_del', 'as' => 'coursecategories.perma_del']);
    Route::resource('coursetags', 'Admin\CoursetagsController');
    Route::post('coursetags_mass_destroy', ['uses' => 'Admin\CoursetagsController@massDestroy', 'as' => 'coursetags.mass_destroy']);
    Route::post('coursetags_restore/{id}', ['uses' => 'Admin\CoursetagsController@restore', 'as' => 'coursetags.restore']);
    Route::delete('coursetags_perma_del/{id}', ['uses' => 'Admin\CoursetagsController@perma_del', 'as' => 'coursetags.perma_del']);
    Route::resource('courses', 'Admin\CoursesController');
    Route::post('courses_mass_destroy', ['uses' => 'Admin\CoursesController@massDestroy', 'as' => 'courses.mass_destroy']);
    Route::post('courses_restore/{id}', ['uses' => 'Admin\CoursesController@restore', 'as' => 'courses.restore']);
    Route::delete('courses_perma_del/{id}', ['uses' => 'Admin\CoursesController@perma_del', 'as' => 'courses.perma_del']);
    Route::resource('coursescertificates', 'Admin\CoursescertificatesController');
    Route::post('coursescertificates_mass_destroy', ['uses' => 'Admin\CoursescertificatesController@massDestroy', 'as' => 'coursescertificates.mass_destroy']);
    Route::post('coursescertificates_restore/{id}', ['uses' => 'Admin\CoursescertificatesController@restore', 'as' => 'coursescertificates.restore']);
    Route::delete('coursescertificates_perma_del/{id}', ['uses' => 'Admin\CoursescertificatesController@perma_del', 'as' => 'coursescertificates.perma_del']);
    Route::resource('faq_categories', 'Admin\FaqCategoriesController');
    Route::post('faq_categories_mass_destroy', ['uses' => 'Admin\FaqCategoriesController@massDestroy', 'as' => 'faq_categories.mass_destroy']);
    Route::resource('faq_questions', 'Admin\FaqQuestionsController');
    Route::post('faq_questions_mass_destroy', ['uses' => 'Admin\FaqQuestionsController@massDestroy', 'as' => 'faq_questions.mass_destroy']);
    Route::resource('generals', 'Admin\GeneralsController');
    Route::post('generals_mass_destroy', ['uses' => 'Admin\GeneralsController@massDestroy', 'as' => 'generals.mass_destroy']);
    Route::post('generals_restore/{id}', ['uses' => 'Admin\GeneralsController@restore', 'as' => 'generals.restore']);
    Route::delete('generals_perma_del/{id}', ['uses' => 'Admin\GeneralsController@perma_del', 'as' => 'generals.perma_del']);
    Route::resource('trailcategories', 'Admin\TrailcategoriesController');
    Route::post('trailcategories_mass_destroy', ['uses' => 'Admin\TrailcategoriesController@massDestroy', 'as' => 'trailcategories.mass_destroy']);
    Route::post('trailcategories_restore/{id}', ['uses' => 'Admin\TrailcategoriesController@restore', 'as' => 'trailcategories.restore']);
    Route::delete('trailcategories_perma_del/{id}', ['uses' => 'Admin\TrailcategoriesController@perma_del', 'as' => 'trailcategories.perma_del']);
    Route::resource('trailtags', 'Admin\TrailtagsController');
    Route::post('trailtags_mass_destroy', ['uses' => 'Admin\TrailtagsController@massDestroy', 'as' => 'trailtags.mass_destroy']);
    Route::post('trailtags_restore/{id}', ['uses' => 'Admin\TrailtagsController@restore', 'as' => 'trailtags.restore']);
    Route::delete('trailtags_perma_del/{id}', ['uses' => 'Admin\TrailtagsController@perma_del', 'as' => 'trailtags.perma_del']);
    Route::resource('trails', 'Admin\TrailsController');
    Route::post('trails_mass_destroy', ['uses' => 'Admin\TrailsController@massDestroy', 'as' => 'trails.mass_destroy']);
    Route::post('trails_restore/{id}', ['uses' => 'Admin\TrailsController@restore', 'as' => 'trails.restore']);
    Route::delete('trails_perma_del/{id}', ['uses' => 'Admin\TrailsController@perma_del', 'as' => 'trails.perma_del']);
    Route::resource('trailscertificates', 'Admin\TrailscertificatesController');
    Route::post('trailscertificates_mass_destroy', ['uses' => 'Admin\TrailscertificatesController@massDestroy', 'as' => 'trailscertificates.mass_destroy']);
    Route::post('trailscertificates_restore/{id}', ['uses' => 'Admin\TrailscertificatesController@restore', 'as' => 'trailscertificates.restore']);
    Route::delete('trailscertificates_perma_del/{id}', ['uses' => 'Admin\TrailscertificatesController@perma_del', 'as' => 'trailscertificates.perma_del']);
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('teams', 'Admin\TeamsController');
    Route::post('teams_mass_destroy', ['uses' => 'Admin\TeamsController@massDestroy', 'as' => 'teams.mass_destroy']);

app/Http/Controllers/Admin/TrailcategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Trailcategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreTrailcategoriesRequest;
use App\Http\Requests\Admin\UpdateTrailcategoriesRequest;
use Yajra\DataTables\DataTables;

use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
class TrailcategoriesController extends Controller
{
    /**
     * Display a listing of Trailcategory.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('trailcategory_access')) {
            return abort(401);
        }


        
        if (request()->ajax()) {
            $query = Trailcategory::query();
            $template = 'actionsTemplate';
            if(request('show_deleted') == 1) {
                
        if (! Gate::allows('trailcategory_delete')) {
            return abort(401);
        }
                $query->onlyTrashed();
                $template = 'restoreTemplate';
            }
            $query->select([
                'trailcategories.id',
                'trailcategories.title',
                'trailcategories.slug',
            ]);
            $table = Datatables::of($query);

            $table->setRowAttr([
                'data-entry-id' => '{{$id}}',
            ]);
            $table->addColumn('massDelete', '&nbsp;');
            $table->addColumn('actions', '&nbsp;');
            $table->editColumn('actions', function ($row) use ($template) {
                $gateKey  = 'trailcategory_';
                $routeKey = 'admin.trailcategories';

                return view($template, compact('row', 'gateKey', 'routeKey'));
            });
            $table->editColumn('title', function ($row) {
                return $row->title ? $row->title : '';
            });
            $table->editColumn('slug', function ($row) {
                return $row->slug ? $row->slug : '';
            });

            $table->rawColumns(['actions','massDelete']);

            return $table->make(true);
        }

        $generals = \App\General::get();
        return view('admin.trailcategories.index', compact('generals'));
    }

    /**
     * Show the form for creating new Trailcategory.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (! Gate::allows('trailcategory_create')) {
            return abort(401);
        }

        $generals = \App\General::get();

        return view('admin.trailcategories.create', compact('generals'));
    }

    /**
     * Store a newly created Trailcategory in storage.
     *
     * @param  \App\Http\Requests\StoreTrailcategoriesRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreTrailcategoriesRequest $request)
    {
        if (! Gate::allows('trailcategory_create')) {
            return abort(401);
        }
        $trailcategory = Trailcategory::create($request->all());



        return redirect()->route('admin.trailcategories.index');
    }


    /**
     * Show the form for editing Trailcategory.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (! Gate::allows('trailcategory_edit')) {
            return abort(401);
        }
        $trailcategory = Trailcategory::findOrFail($id);

        $generals = \App\General::get();

        return view('admin.trailcategories.edit', compact('trailcategory', 'generals'));
    }

    /**
     * Update Trailcategory in storage.
     *
     * @param  \App\Http\Requests\UpdateTrailcategoriesRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateTrailcategoriesRequest $request, $id)
    {
        if (! Gate::allows('trailcategory_edit')) {
            return abort(401);
        }
        $trailcategory = Trailcategory::findOrFail($id);
        $trailcategory->update($request->all());



        return redirect()->route('admin.trailcategories.index');
    }


    /**
     * Display Trailcategory.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (! Gate::allows('trailcategory_view')) {
            return abort(401);
        }
        $trails = \App\Trail::whereHas('categories',
                    function ($query) use ($id) {
                        $query->where('id', $id);
                    })->get();

        $trailcategory = Trailcategory::findOrFail($id);

        $generals = \App\General::get();

        return view('admin.trailcategories.show', compact('trailcategory', 'trails', 'generals'));
    }


    /**
     * Remove Trailcategory from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (! Gate::allows('trailcategory_delete')) {
            return abort(401);
        }
        $trailcategory = Trailcategory::findOrFail($id);
        $trailcategory->delete();

        return redirect()->route('admin.trailcategories.index');
    }

    /**
     * Delete all selected Trailcategory at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        if (! Gate::allows('trailcategory_delete')) {
            return abort(401);
        }
        if ($request->input('ids')) {
            $entries = Trailcategory::whereIn('id', $request->input('ids'))->get();

            foreach ($entries as $entry) {
                $entry->delete();
            }
        }
    }


    /**
     * Restore Trailcategory from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function restore($id)
    {
        if (! Gate::allows('trailcategory_delete')) {
            return abort(401);
        }
        $trailcategory = Trailcategory::onlyTrashed()->findOrFail($id);
        $trailcategory->restore();

        return redirect()->route('admin.trailcategories.index');
    }

    /**
     * Permanently delete Trailcategory from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function perma_del($id)
    {
        if (! Gate::allows('trailcategory_delete')) {
            return abort(401);
        }
        $trailcategory = Trailcategory::onlyTrashed()->findOrFail($id);
        $trailcategory->forceDelete();

        return redirect()->route('admin.trailcategories.index');
    }
}

app/Http/Controllers/Api/V1/TrailcategoriesController.php
<?php

namespace App\Http\Controllers\Api\V1;

use App\Trailcategory;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreTrailcategoriesRequest;
use App\Http\Requests\Admin\UpdateTrailcategoriesRequest;
use Yajra\DataTables\DataTables;

use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
class TrailcategoriesController extends Controller
{
    public function index()
    {
        return Trailcategory::all();
    }

    public function show($id)
    {
        return Trailcategory::findOrFail($id);
    }

    public function update(UpdateTrailcategoriesRequest $request, $id)
    {
        $trailcategory = Trailcategory::findOrFail($id);
        $trailcategory->update($request->all());
        

        return $trailcategory;
    }

    public function store(StoreTrailcategoriesRequest $request)
    {
        $trailcategory = Trailcategory::create($request->all());
        

        return $trailcategory;
    }

    public function destroy($id)
    {
        $trailcategory = Trailcategory::findOrFail($id);
        $trailcategory->delete();
        return '';
    }
}

resources/views/admin/trailcategories/index.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')

@section('content')
    <div class="page-title">
        <div class="row">
            <div class="col s12 m8"><h1>@lang('global.trailcategories.title')</h1>
                <ul>
                    <li>
                        <a href="{{ url('/admin/home') }}">
                            <i class="fa fa-home"></i>
                            Dashboard</a>
                    </li> /
                    <li><span>@lang('global.trailcategories.title')</span></li>
                </ul>
            </div>
            <div class="col s12 m4 right-align">

                @can('trailcategory_create')
                    <a href="{{ route('admin.trailcategories.create') }}" class="btn lighten-3 z-depth-0 chat-toggle">
                        Add Category
                    </a>
                @endcan
            </div>
        </div>
    </div>
    
    <ul class="tabs z-depth-1">
        <li class="tab">
            <a href="{{ route('admin.trailcategories.index') }}" class="grey-text {{ request('show_deleted') == 1 ? '' : 'active' }}">@lang('global.app_all')</a>
        </li>
        <li class="tab">
            <a href="{{ route('admin.trailcategories.index') }}?show_deleted=1" class="grey-text {{ request('show_deleted') == 1 ? 'active' : '' }}">@lang('global.app_trash')</a>
        </li>
    </ul>

    <div class="card">
        <div class="title">
            <h3>@lang('global.app_list')</h3>
        </div>

        <div class="content">
            <table class="no-order table table-striped ajaxTable @can('trailcategory_delete') @if ( request('show_deleted') != 1 ) dt-select @else dt-show @endif @endcan">
                <thead>
                    <tr>
                        <th>@lang('global.app_order')</th>
                        @can('trailcategory_delete')
                            @if ( request('show_deleted') != 1 )<th><input type="checkbox" id="select-all" /><label for="select-all"></label></th>@endif
                        @endcan

                        <th>@lang('global.trailcategories.fields.title')</th>
                        <th>@lang('global.trailcategories.fields.slug')</th>
                        @if( request('show_deleted') == 1 )
                        <th>&nbsp;</th>
                        @else
                        <th>&nbsp;</th>
                        @endif
                    </tr>
                </thead>
            </table>
        </div>
    </div>
@stop

@section('javascript') 
    <script>
        @can('trailcategory_delete')
            @if ( request('show_deleted') != 1 ) window.route_mass_crud_entries_destroy = '{{ route('admin.trailcategories.mass_destroy') }}'; @endif
        @endcan
        $(document).ready(function () {
            window.dtDefaultOptions.ajax = '{!! route('admin.trailcategories.index') !!}?show_deleted={{ request('show_deleted') }}';
            window.dtDefaultOptions.columns = [
                {data: 'title', name: 'title'},
                @can('trailcategory_delete')
                    @if ( request('show_deleted') != 1 )
                        {data: 'massDelete', name: 'id', searchable: false, sortable: false},
                    @endif
                @endcan
                {data: 'title', name: 'title'},
                {data: 'slug', name: 'slug'},
                
                {data: 'actions', name: 'actions', searchable: false, sortable: false}
            ];
            processAjaxTables();
        });
    </script>
@endsection

resources/views/admin/trailcategories/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="page-title">
        <div class="row">
            <div class="col s12 m9 l10"><h1>@lang('global.trailcategories.title')</h1>
                <ul>
                    <li>
                        <a href="{{ url('/admin/home') }}">
                            <i class="fa fa-home"></i>
                            Dashboard</a>
                    </li> /
                    <li>
                        <a href="{{ route('admin.trailcategories.index') }}">
                            @lang('global.trailcategories.title')</a>
                    </li> /
                    <li><span>{{ $trailcategory->title }}</span></li>
                </ul>
            </div>
            <div class="col s12 m3 l2 right-align">
                <a href="{{ route('admin.trailcategories.index') }}" class="btn lighten-3 z-depth-0 chat-toggle">
                    @lang('global.app_back_to_list')
                </a>
            </div>
        </div>
    </div>

    <div class="card">
        <div class="title">
            <h5>@lang('global.app_view')</h5>
        </div>

        <div class="content">
            <div class="row">
                <div class="col s6">
                    <table class="table table-striped">
                        <tr>
                            <th>@lang('global.trailcategories.fields.title')</th>
                            <td field-key='title'>{{ $trailcategory->title }}</td>
                        </tr>
                        <tr>
                            <th>@lang('global.trailcategories.fields.slug')</th>
                            <td field-key='slug'>{{ $trailcategory->slug }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-tabs">
            <ul class="shuffle-tabs tabs tabs-fixed-width">
                <li class="tab grey-text active"><a class="grey-text" href="#trails">Trails</a></li>
            </ul>
        </div>

        <div class="content">
            
            <div class="active" id="trails">
                <table class="striped responsive-table {{ count($trails) > 0 ? 'datatable' : '' }}">
                    <thead>
                        <tr>
                            <th>@lang('global.trails.fields.order')</th>
                            <th>@lang('global.trails.fields.title')</th>
                            {{--<th>@lang('global.trails.fields.slug')</th>--}}
                            {{--<th>@lang('global.trails.fields.description')</th>--}}
                            {{--<th>@lang('global.trails.fields.introduction')</th>--}}
                            {{--<th>@lang('global.trails.fields.featured-image')</th>--}}
{{--                            <th>@lang('global.trails.fields.courses')</th>--}}
                            <th>@lang('global.trails.fields.start-date')</th>
                            <th>@lang('global.trails.fields.end-date')</th>
                            {{--<th>@lang('global.trails.fields.categories')</th>--}}
                            {{--<th>@lang('global.trails.fields.tags')</th>--}}
                            <th>@lang('global.trails.fields.approved')</th>
                            @if( request('show_deleted') == 1 )
                            <th>&nbsp;</th>
                            @else
                            <th>&nbsp;</th>
                            @endif
                        </tr>
                    </thead>

                    <tbody>
                        @if (count($trails) > 0)
                            @foreach ($trails as $trail)
                                <tr data-entry-id="{{ $trail->id }}">
                                    <td field-key='order'>{{ $trail->order }}</td>
                                    <td field-key='title'>{{ $trail->title }}</td>
                                    {{--<td field-key='slug'>{{ $trail->slug }}</td>--}}
                                    {{--<td field-key='description'>{!! $trail->description !!}</td>--}}
                                    {{--<td field-key='introduction'>{!! $trail->introduction !!}</td>--}}
                                    {{--<td field-key='featured_image'>{{ $trail->featured_image }}</td>--}}
                                    {{--<td field-key='courses'>--}}
                                        {{--@foreach ($trail->courses as $singleCourses)--}}
                                            {{--<span class="label label-info label-many">{{ $singleCourses->title }}</span>--}}
                                        {{--@endforeach--}}
                                    {{--</td>--}}
                                    <td field-key='start_date'>{{ $trail->start_date }}</td>
                                    <td field-key='end_date'>{{ $trail->end_date }}</td>
                                    {{--<td field-key='categories'>--}}
                                        {{--@foreach ($trail->categories as $singleCategories)--}}
                                            {{--<span class="label label-info label-many">{{ $singleCategories->title }}</span>--}}
                                        {{--@endforeach--}}
                                    {{--</td>--}}
                                    {{--<td field-key='tags'>--}}
                                        {{--@foreach ($trail->tags as $singleTags)--}}
                                            {{--<span class="label label-info label-many">{{ $singleTags->title }}</span>--}}
                                        {{--@endforeach--}}
                                    {{--</td>--}}
                                    <td field-key='approved'>{{ Form::checkbox("approved", 1, $trail->approved == 1 ? true : false, ["disabled"]) }}</td>
                                    @if( request('show_deleted') == 1 )
                                    <td>
                                        {!! Form::open(array(
                                            'style' => 'display: inline-block;',
                                            'method' => 'POST',
                                            'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                            'route' => ['admin.trails.restore', $trail->id])) !!}
                                        {!! Form::submit(trans('global.app_restore'), array('class' => 'btn-square blue-text')) !!}
                                        {!! Form::close() !!}
                                                                        {!! Form::open(array(
                                            'style' => 'display: inline-block;',
                                            'method' => 'DELETE',
                                            'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                            'route' => ['admin.trails.perma_del', $trail->id])) !!}
                                        {!! Form::submit(trans('global.app_permadel'), array('class' => 'btn-square red-text')) !!}
                                        {!! Form::close() !!}
                                                                    </td>
                                    @else
                                    <td class="actions">
                                        <div class="buttons d-flex align-items-center justify-content-center">
                                            @can('trail_view')
                                            <a href="{{ route('admin.trails.show',[$trail->id]) }}" class="waves-effect waves-light btn-small btn-square amber-text"><i class="material-icons">remove_red_eye</i></a>
                                            @endcan
                                            @can('trail_edit')
                                            <a href="{{ route('admin.trails.edit',[$trail->id]) }}" class="waves-effect waves-light btn-small btn-square blue-text"><i class="material-icons">edit</i></a>
                                            @endcan
                                            @can('trail_delete')
                                            {!! Form::open(array(
                                                'style' => 'display: inline-block;',
                                                'method' => 'DELETE',
                                                'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                                'route' => ['admin.trails.destroy', $trail->id])) !!}
                                            {!! Form::button('<i class="far fa-trash-alt"></i>', ['class'=>'waves-effect waves-light btn-small btn-square red-text', 'type'=>'submit']) !!}
                                            {!! Form::close() !!}
                                            @endcan
                                        </div>
                                    </td>
                                    @endif
                                </tr>
                            @endforeach
                        @else
                            <tr>
                                <td colspan="17">@lang('global.app_no_entries_in_table')</td>
                            </tr>
                        @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@stop